### ISSUE TITLE
how to use tishadow to run a app in two devices at one time

### ISSUE THREAD

**Issue by terry2010** [dbankier/TiShadow#357]
for development , I just want run app in ios and android device , I tried this 

titanium build --platform iphone --target simulator --shadow

it works , 

but I do this 

titanium build -p android -T device --shadow 

it says:

> [INFO] Beginning Build Process
> [WARN] Nothing to update.
> [ERROR] Failed to start server on port: 3000
> [INFO] [iphone, 8.0, 192.168.199.211] Connected
> [ERROR] TiShadow Server exited.

 how to point a custom port to this ? thank you very much

ps: I tried   titanium build -p android -T device --shadow  --port 3001 , it didn't works

**Comment by CaptainQuirk** [comment]
Hi,

I'm reopening this because I cannot get it working anymore.

I'm launching the server with
```
ts server
```

I'm launching the iOS simulator with
```
/usr/local/Cellar/node012/0.12.7/bin/node /usr/local/bin/ti --sdk 3.5.1.GA build --log-level debug --platform ios --project-dir /Users/me/Documents/A
pps/superapp/build/appify --no-banner --no-progress-bars --no-prompt --sdk 3.5.1.GA --command build --target simulator --deploy-type development --pp-uu
id xxxxxxxxxxxxxxx --device-id 6A50C175-8E2C-473F-B16F-03366649AC1B  --appify --express
```

And the android simulator with
```
/usr/local/Cellar/node012/0.12.7/bin/node /usr/local/bin/ti --sdk 3.5.1.GA build --log-level debug --platform android --project-dir /Users/me/Documen
ts/Apps/superapp/build/appify --no-banner --no-progress-bars --no-prompt --command build --deploy-type development --device-id Samsung Galaxy S5 - 4.4.4
 - API 19 - 1080x1920 --appify --express
```

I start watching files with
```
ts @ run --update
```


This last command relaunches compilation for both targets but __my iOS simulator hangs on the application splash screen__, even if I try to restart the application after having killed it.

One thing worh mentioning it that for both targets  the __appify flag is missing__ in the command launched automatically by ``` ts @ run --update```. 

I'm using 
  * __node v0.12.7__
  * __Titanium cli 5.0.5__
  * __TiShadow 2.8.3__

I'm on Mac OS X, El Capitan

Any help would be appreciated !

Thanks
