### ISSUE TITLE
--shadow not working for basic Android on device

### ISSUE THREAD

**Issue by wpccolorblind** [dbankier/TiShadow#397]
1.  "ti create" a new android app
2.  cd into app dir
3.  ti build -p android -T device --shadow

Expected --
Launches app where live refreshes work.

Actual --
Launches app.  Changing something in Resources/app.js doesn't trigger refresh.  Same steps work to execute live refresh on ios for command "ti build -p ios -f --debug --skip-js-minify --target device --pp-uuid <uuid> -V <developer name> --shadow"

Also tried an Alloy app.

Any ideas?  I'm trying to get a min setup going that does the live refresh to both an android and ios device at the same time.  ios works, but can't seem to get the most basic android example working.

Thanks!

**Comment by m1ga** [comment]
it will build a normal app in my test when I run 3. 
If I run tishadow appify it will end with an error:
~~~
[INFO] Bundle Ready: /home/miga/dev/titanium/app/build/tishadow/dist/app.zip
[ERROR] You really don't want to write to the current directory.
~~~

the zip is inside the folder but it still show the error. Perhaps thats somehow related.

And you have to connect a device via usb otherwise 3. won't even start (won't find any device)

**Comment by dbankier** [comment]
@wpccolorblind
Windows or osx?
Did you install globally with the `--unsafe-perm` flag?
What version ti and tishadow?

**Comment by wpccolorblind** [comment]
@dbankier 

-- osx yosemite
-- confirmed global install with --unsafe-perm
-- ti 3.5.0
-- tishadow 2.7.5

**Comment by dbankier** [comment]
is you device on the same network?

**Comment by wpccolorblind** [comment]
@dbankier that was it!  Had wifi disabled on that device.  Working great now, thanks!
