### ISSUE TITLE
Infinite loop with alloy.jmk file

### ISSUE THREAD

**Issue by filaruina** [dbankier/TiShadow#424]
Hi,

I'm starting my project with `titanium build -p android -T device --shadow` and it used to work fine. But we had to create a `pre:compile` script to download some files and change the localization files, that is now causing shadow to go on an infinite loop. I imagine that is caused because he watches the files that are changed later.
Any way to support this kind of thing? I think that it might be useful in some use cases that an .jmk is used to change some files before alloy compilation.

**Comment by dbankier** [comment]
Have a look at #410 and what was implemented to save that. Not sure if it will help in your case.
Other than excluding files from watch, not sure what else I can do.

FWIW, personally I prefer using grunt/gulp for preprocessing rather than hacking the .jmk. It is easier to scale and manage dependencies. 
Have a look at https://github.com/dbankier/JAST as an example.

**Comment by filaruina** [comment]
Oh, didn't know you could exclude files from watch, probably missed it in the docs. Exactly what I was looking for. Thanks a lot and sorry for the poor search.

About using JAST and Grunt:
Currently I'm trying to keep dependencies to a minimum due to the nature of the project and how it will integrate with some already existing projects. That said using grunt would be great for that but wouldn't help so much as a whole. Anyway, I'm using some of the things included in JAST =)
