### ISSUE TITLE
Tishadow no update

### ISSUE THREAD

**Issue by koolll** [dbankier/TiShadow#492]
First of all , thanks for your contribution .I am using genymotion together with tishadow. 
This is the command i use in terminal
**appc ti build -p android --device-id "Google Nexus 5 - 6.0.0 - API 23 - 1080x1920" --shadow** 

The emulator can be start but once i made any file changes and save it. The apps will be restart , but the apps is not updated. 
Browse to localhost:3000 and yes the device is connected.  
Any solution for this ? 

Thanks

**Comment by yomybaby** [comment]
Since Android 6.0, Android has different permission system. 
Unfortunately current tishadow, you have to give storage permission to tidhadow on Setting App( Settings > Application > your app > permissions > storage ...)
Then tishadow works properly on Android 6. 

I think that it will be improved in the near feature.

**Comment by dbankier** [comment]
Yes. I'm aware of this. I used a native module in the container app that is on the PlayStore, but I was holding off pushing it as it will be in 5.3.1...

**Comment by koolll** [comment]
hi thanks for your comment. I having another issue now. My apps keep restart and command prompt keep loading. I already update the tishadow to 2.8.6

Did i miss anything. I am using genymotion with Tishadow

**Comment by koolll** [comment]
Problem fix. I need to update the titanium cli also. Thanks. Please close this post
